<?php
	$data_source="sqlite:/path/to/ping.db3";
	$auth_methods["local"]=true;
	$auth_methods["system"]=false;
	$pepper="YOUR_PEPPER_HERE";
	$system_main="http://account.kitinfo.de/verify/";
	$system_user="system_user";
	$system_password="system_pass";
?>
